### ISSUE TITLE
LPISP distance

### ISSUE THREAD

**Issue by affromero** [HsinYingLee/DRIT#24]
Could you please provide more details about the evaluation. You mentioned 1000 pairs of randomly sampled images translated from 100 images, that is 10 pairs per image (20 fixed random styles for the whole set?), and then the average?
Thank you.

**Comment by HsinYingLee** [comment]
I think there are possible several settings can be used:
1. If you would like to compare with the ground truth set and other methods, say, a collection of N images. You can translate N target images from N source images. Then you can randomly sample M pairs out of this N images to calculate the diversity.
2. Other way to compare among different methods is, given N source images, for each image, you translate M of them and calculate a diversity score among these M target images. You then average the score of all N images.

We use the first setting in our experiments. Since there's no standard setting in this kind of experiment yet, I believe any setting that makes same should be okay.
