### ISSUE TITLE
[Paper] Swapping attribute rep. or content rep. ?

### ISSUE THREAD

**Issue by TheIllusion** [HsinYingLee/DRIT#25]
Hi, 
I have a question regarding the cross-cycle consistency loss.

By the way, I saw your ECCV 2018 oral presentation in Munich and I greatly inspired by your work. 
Thanks. 

According to the paper, the attribute representations are swapped during the translation stage to calculate the cross-cycle consistency loss.

However, as far as I understand, the content representations are swapped when I look the expressions carefully. 

Is my understanding correct? (I can't be sure about my understanding infact...)

<img width="841" alt="2018-12-15 11 54 53" src="https://user-images.githubusercontent.com/19279856/50038290-83d2c700-0060-11e9-8203-293635a282ad.png">

<img width="822" alt="2018-12-15 12 10 03" src="https://user-images.githubusercontent.com/19279856/50038393-643c9e00-0062-11e9-9464-090b56295f95.png">

**Comment by HsinYingLee** [comment]
Hi, 

The expression is indeed a little bit ambiguous. Since we only have two domains, "fix content, swap attribute" and "fix attribute, swap content" are the same in the implementation point of view. From the perspective of each domain, it is "swap the content"; From the perspective of contour/shape, it is "swap the attribute".

**Comment by TheIllusion** [comment]
Thanks! Now it's clear.
