### ISSUE TITLE
Why use double discriminators for each domain?

### ISSUE THREAD

**Issue by DAA233** [HsinYingLee/DRIT#32]
Thanks for your awesome work!

I see the there are two discriminators for each domain, which are `disA` and `disA2` for domain A, `disB` and `disB2` for domain B. I have noticed that they are updated with different inputs. However, I don't know if double discriminators are necessary here.

Have I missed something in the paper? Could you explain a little more about this?

**Comment by HsinYingLee** [comment]
Thank you for your interests.

It's first used in the original CycleGAN. One discriminator is used for the translated images, while the other is used for images generated from random noise. I think it's not theoretically necessary but it can facilitate the training process since two distributions are quite different in practice.

**Comment by DAA233** [comment]
I see. Thank you a lot!
